repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black .
      language: system
      types: [ python ]
    - id: pylint
      name: pylint
      entry: pylint auth2guard
      language: system
      types: [python]
      args:
        [
          "--disable",
          "E0611,C0114,C0115,C0116",
          "--ignore-paths",
          "tests/",
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [ python ]
      pass_filenames: false
    - id: mutatest
      name: mutatest
      entry: mutatest
      language: system
      types: [ python ]
      args:
        [
          "-n",
          "100",
          "-s",
          "auth2guard",
        ]
      pass_filenames: false
